---
title: "Lab 07 - Linear Regression"
author: Chu-Chun Ku
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: simplex
    number_sections: false
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

## 0 load the package and suppress scientific notation 
```{r}
# load packages 
library(ggplot2)

# not display scientific notation
options(scipen=999)
```

## 1 create a data frame 

```{r}
library(tidyverse)
# read data from a csv file 
housing.df <- read_csv("ameshousing.csv")
# first six rows 
head(housing.df)
# column names 
names(housing.df)
```

## 2 identify thresholds of 4 bins with an equal number of observations 
```{r}
bins <- quantile(housing.df$Gr_Liv_Area, probs = c(0,0.25,0.5,0.75,1))
bins


```

## 3 bin Gr_Liv_Area   
```{r}
# remove the names of a named vector 
bins <- unname(bins)
# bin Gr_Liv_Area 
housing.df$Gr_Liv_Area_bin <- .bincode(housing.df$Gr_Liv_Area, bins, include.lowest = TRUE)
# first six values of Gr_Liv_Area_bin
head(housing.df$Gr_Liv_Area_bin)
# data type of Gr_Liv_Area_bin
str(housing.df$Gr_Liv_Area_bin)
```

## 4 fit a regression model with an ordinal categorical predictor 
```{r}
lm <- lm(formula = SalePrice ~ as.factor(Gr_Liv_Area_bin), data = housing.df)
summary(lm)

```

## 5 calculate the mean of Sale Price for each value in Gr_Liv_Area_bin
```{r}
# mean of SalePrice for each value in Gr_Liv_Area_bin 
summary_housing <- housing.df %>%
  group_by(Gr_Liv_Area_bin) %>%
  summarize(SalePrice_mean = mean(SalePrice))
summary_housing
# group mean difference between category 2 and category 1
group1 <- 105448.0
group2 <- 130211.1
print(group2 - group1)
# group mean difference between category 3 and category 1
group3 <- 150122.1
print(group3 - group1)
# group mean difference between category 4 and category 1
group4 <- 164648.4
print(group4 - group1)
```

## 6 plot the mean of Sale Price for each value in Gr_Liv_Area_bin
```{r}
gg <- ggplot(summary_housing, aes(x=Gr_Liv_Area_bin, y=SalePrice_mean)) +
  geom_col(stat = "identity", fill = "darkgray") +
  labs(y = "SalePrice") +
  theme_gray()
gg

```
